# Generated by Django 3.1.7 on 2021-03-19 22:52

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Имя')),
                ('anons', models.CharField(max_length=250, verbose_name='Мероприятие')),
                ('full_text', models.TextField(verbose_name='Обратная связь')),
                ('date', models.DateTimeField(verbose_name='Дата отправки')),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('dolznost', models.CharField(max_length=50, verbose_name='Должность')),
                ('Zadanie1', models.CharField(blank=True, default='-', max_length=20, verbose_name='Задание 1')),
                ('Zadanie2', models.CharField(blank=True, default='-', max_length=20, verbose_name='Задание 2')),
                ('Zadanie3', models.CharField(blank=True, default='-', max_length=20, verbose_name='Задание 3')),
                ('Zadanie4', models.CharField(blank=True, default='-', max_length=20, verbose_name='Задание 4')),
                ('zp', models.CharField(max_length=20, verbose_name='Заработная плата')),
            ],
            options={
                'verbose_name': 'Сотрудника',
                'verbose_name_plural': 'Сотрудники',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
